---
- name: generate hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: generate systemd-resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  notify: restart resolved

- name: start systemd-resolved
  service:
    name: systemd-resolved
    state: started
    enabled: yes

- name: use systemd-resolved
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
